local plugin_root = vim.fn.getcwd()
vim.opt.rtp:prepend(plugin_root)
vim.opt.rtp:prepend(vim.env.REVIEW_TEST_CODEX or vim.fs.dirname(plugin_root) .. "/codex-cli.nvim")
package.path = plugin_root .. "/tests/?.lua;" .. package.path
vim.env.XDG_DATA_HOME = vim.fn.tempname()
vim.o.columns, vim.o.lines = 120, 40
local api, h = vim.api, require("helpers")
local review = require("review")
review.setup({ auto_advance = false })
require("codex_cli").setup({ chat = { history = false, instructions_file = false,
  command = { "python3", (vim.env.REVIEW_TEST_CODEX or vim.fs.dirname(plugin_root) .. "/codex-cli.nvim") .. "/tests/fake_server.py" } } })
local chat = require("codex_cli.chat")
local root = h.project()
local ok, err = xpcall(function()
  vim.cmd("cd " .. vim.fn.fnameescape(root))
  vim.cmd.edit(root .. "/a.lua")
  local source = api.nvim_get_current_buf()
  review.open({ root = root })
  review.mark("REJECT")
  review.close()
  assert(not vim.bo[source].modified)
  chat.open()
  chat.mode()
  chat.send("Explain the reviewed fix")
  local session = chat._ui.session
  assert(vim.wait(5000, function() return not session.busy end, 10))
  assert(session.messages[#session.messages].text:find("안녕", 1, true), "Codex apply request must proceed immediately after review")
  api.nvim_buf_set_lines(source, 0, 0, false, { "-- unsaved user edit" })
  local count = #session.messages
  chat.send("Keep protecting actual unsaved edits")
  h.equal(#session.messages, count, "Actual unsaved source edits must still block Codex apply")
  chat.close()
  session.rpc:stop()
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: review decision -> exit -> Codex apply; actual unsaved source stays protected")
vim.cmd("qa!")
