vim.opt.rtp:prepend(vim.fn.getcwd())
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
root = vim.uv.fs_realpath(root)
local function git(args)
  local cmd = { "git", "-C", root }; vim.list_extend(cmd, args)
  local r = vim.system(cmd, { text = true }):wait(); assert(r.code == 0, r.stderr)
end
local function write(lines) vim.fn.writefile(lines, root .. "/screen.tsx") end
local diff, store = require("review.local_diff"), require("review.store")
local ok, err = xpcall(function()
  git({ "init", "-q" })
  write({ "import {", "  type OldType,", "} from 'module'", "import old from 'old'", "", "export const value = 1" })
  git({ "add", "." }); git({ "-c", "user.name=Test", "-c", "user.email=test@example.test", "commit", "-qm", "base" })
  write({ "import {", "  type NewType,", "} from 'module'", "import newer from 'new'", "", "export const value = 1" })
  local r = diff.apply(root)
  assert(r.created == 0 and #r.skipped == 1, vim.inspect(r))
  write({ "import {", "  type NewType,", "} from 'module'", "import newer from 'new'", "", "export const value = 2" })
  assert(diff.apply(root).created == 1, "Mixed logic/import changes must remain reviewable")
  write({ "import {", "  type NewType,", "} from 'module'", "import newer from 'new'", "", "export const value = 1" })
  assert(diff.apply(root).archived == 1, "Obsolete import-only local point must be archived")
  write({ "", "export const value = 1" })
  assert(diff.apply(root).created == 0, "Removed imports must also be excluded")
  vim.fn.writefile({ "export const lazy = () => import('module')" }, root .. "/lazy.ts")
  assert(diff.apply(root).created == 1, "Dynamic imports are executable code")
end, debug.traceback)
vim.fn.delete(root, "rf"); vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: single/multiline import-only changes, removals, mixed logic, dynamic imports and obsolete point archival")
vim.cmd("qa!")
