vim.opt.rtp:prepend(vim.fn.getcwd())
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
root = vim.uv.fs_realpath(root)
local function git(args)
  local cmd = { "git", "-C", root }; vim.list_extend(cmd, args)
  local r = vim.system(cmd, { text = true }):wait()
  assert(r.code == 0, r.stderr)
end
local function write(path, lines) vim.fn.writefile(lines, root .. "/" .. path) end
local store, diff = require("review.store"), require("review.local_diff")
local function active()
  return vim.tbl_filter(function(i) return not i.archived end, store.load(root).items)
end
local ok, err = xpcall(function()
  git({ "init", "-q" })
  write("app.lua", { "local value = 1", "return value" })
  assert(diff.apply(root).created == 1, "Unborn repository must review untracked source")
  git({ "add", "." }); git({ "-c", "user.name=Test", "-c", "user.email=test@example.test", "commit", "-qm", "initial" })
  write("app.lua", { "local value = 2", "return value" })
  git({ "add", "app.lua" })
  write("app.lua", { "local value = 3", "return value" })
  write("new file.lua", { "return 'new'" })
  write("app.test.lua", { "test()" })
  vim.fn.mkdir(root .. "/.argent/flows", "p")
  write(".argent/flows/verification.yaml", { "name: verification" })
  write(".settings", { "hidden" })
  vim.fn.mkdir(root .. "/src/.internal", "p")
  write("src/.internal/config.lua", { "return true" })
  local review = require("review")
  review.setup()
  vim.cmd.edit(root .. "/app.lua")
  assert(vim.fn.maparg("\\rl", "n") ~= "", "Local review shortcut must be registered")
  local r = diff.apply(root)
  assert(r.created == 2 and #r.skipped == 4, vim.inspect(r))
  for _, item in ipairs(active()) do
    if item.path == "app.lua" then
      assert(vim.deep_equal(item.anchor, { "local value = 3" }), "Unchanged surrounding code must not be highlighted")
    end
  end
  vim.cmd("ReviewLocal")
  assert(#vim.api.nvim_buf_get_extmarks(0, vim.api.nvim_get_namespaces()["review.nvim"], 0, -1, {}) > 0,
    "Command must display generated points")
  review.stop()
  local data, version = store.load(root)
  for _, i in ipairs(data.items) do i.status = "OK" end
  data.items[#data.items + 1] = { id = "manual", path = "app.lua", row = 2, anchor = { "return value" }, title = "manual", status = "REJECT" }
  store.save(root, data, version)
  vim.cmd("ReviewLocal")
  local marks = vim.api.nvim_buf_get_extmarks(0, vim.api.nvim_get_namespaces()["review.nvim"], 0, -1, { details = true })
  assert(#marks == 1, "Local review must hide unrelated manual/AI points")
  review.close()
  review.toggle()
  marks = vim.api.nvim_buf_get_extmarks(0, vim.api.nvim_get_namespaces()["review.nvim"], 0, -1, {})
  assert(#marks == 1, "Toggle must retain local scope")
  review.open({ root = root, no_jump = true })
  marks = vim.api.nvim_buf_get_extmarks(0, vim.api.nvim_get_namespaces()["review.nvim"], 0, -1, {})
  assert(#marks == 2, "Explicit full review must restore manual/AI points")
  review.stop()
  r = diff.apply(root)
  assert(r.unchanged == 2 and r.created == 0)
  write("app.lua", { "local value = 4", "return value" })
  r = diff.apply(root)
  assert(r.updated == 1 and r.unchanged == 1, vim.inspect(r))
  for _, i in ipairs(active()) do
    if i.id == "manual" then assert(i.status == "REJECT")
    elseif i.path == "app.lua" then assert(i.status == "PENDING")
    else assert(i.status == "OK") end
  end
  git({ "restore", "--staged", "app.lua" }); git({ "restore", "app.lua" })
  vim.fn.delete(root .. "/new file.lua")
  r = diff.apply(root)
  assert(r.archived == 2 and #active() == 1)
  write("app.lua", { "return value" })
  r = diff.apply(root)
  assert(r.created + r.updated == 0 and #r.skipped > 0, "Deletion-only hunk must not highlight unchanged context")
  vim.cmd.edit(root .. "/app.lua")
  vim.api.nvim_buf_set_lines(0, 0, 1, false, { "unsaved" })
  assert(not pcall(diff.apply, root), "Must not review stale disk content over unsaved edits")
  vim.bo.modified = false
  vim.fn.delete(root .. "/app.lua")
  r = diff.apply(root)
  assert(#r.skipped >= 1, "Whole-file deletion must be reported")
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: local staged/unstaged/new files, test exclusion, decisions, updates, cleanup, deletions and unsaved protection")
vim.cmd("qa!")
