vim.opt.rtp:prepend(vim.fn.getcwd())
package.path = vim.fn.getcwd() .. "/tests/?.lua;" .. package.path
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local h, api = require("helpers"), vim.api
local review, store = require("review"), require("review.store")
review.setup()
local root = h.modeline_project()
local ok, err = xpcall(function()
  vim.cmd("cd " .. vim.fn.fnameescape(root))
  vim.o.modelines = 0
  vim.cmd.edit(root .. "/url.lua")
  vim.o.modelines = 5
  local before = vim.fn.readfile(root .. "/url.lua")
  h.equal(review.import({ root = root }), 1, "Legacy comment must migrate")
  h.equal(vim.fn.readfile(root .. "/url.lua"), { "local url = 'https://example.test'", "-- vim: 'https://example.test'" }, "Only marker lines may be removed")
  h.equal(#store.load(root).items, 1, "Metadata must exist after cleanup")
  local backups = vim.fn.glob(vim.env.XDG_DATA_HOME .. "/nvim/review/backups/*/*.source", false, true)
  h.equal(#backups, 1, "Original source backup must exist")
  h.equal(vim.fn.readfile(backups[1]), before, "Backup must preserve original content")
  assert(not vim.bo.modified, "Clean-file migration should save marker removal")
  review.mark("REJECT")
  assert(not vim.bo.modified, "Later reviews must never reinsert markers")
  h.equal(review.import({ root = root }), 0, "Import must be idempotent")
  review.stop()
  vim.fn.writefile({ "-- REVIEW[REJECT]: unsaved marker", "local value = 1", "-- REVIEW_END" }, root .. "/unsaved.lua")
  vim.cmd.edit(root .. "/unsaved.lua")
  api.nvim_buf_set_lines(0, 1, 2, false, { "local value = 2" })
  h.equal(review.import({ root = root, buffer = true }), 1, "Unsaved buffer migration must be supported")
  h.equal(api.nvim_buf_get_lines(0, 0, -1, false), { "local value = 2" }, "Migration must preserve manual code changes")
  assert(vim.bo.modified, "Manual edits must not be auto-saved")
  assert(vim.fn.readfile(root .. "/unsaved.lua")[1]:find("REVIEW", 1, true), "Unsaved migration must leave disk untouched")
  vim.cmd("silent write")
  review.stop()
  vim.fn.writefile({ "-- REVIEW: keep on failure", "local keep = true", "-- REVIEW_END" }, root .. "/failure.lua")
  local path = store.path(root)
  vim.fn.writefile({ "broken JSON" }, path)
  h.equal(review.import({ root = root }), 0, "Corrupt metadata must block migration")
  assert(vim.fn.readfile(root .. "/failure.lua")[1]:find("REVIEW",1,true), "Failed storage must preserve source comments")
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: backup-before-removal migration, status preservation, idempotence and failure protection")
vim.cmd("qa!")
