vim.opt.rtp:prepend(vim.fn.getcwd())
package.path = vim.fn.getcwd() .. "/tests/?.lua;" .. package.path
local plugins = vim.env.REVIEW_TEST_PLUGINS or (vim.fn.stdpath("data") .. "/lazy")
vim.opt.rtp:append(plugins .. "/plenary.nvim")
vim.opt.rtp:append(plugins .. "/telescope.nvim")
vim.g.mapleader = " "
vim.o.columns, vim.o.lines = 120, 40
require("telescope").setup({ defaults = { initial_mode = "normal" } })
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local h = require("helpers")
local review = require("review")
local api = vim.api
review.setup({ auto_advance = false })
local root = h.project()
local function wait(predicate, message)
  assert(vim.wait(3000, predicate, 10), message)
end
local ok, err = xpcall(function()
  vim.cmd("cd " .. vim.fn.fnameescape(root))
  vim.cmd.edit(root .. "/a.lua")
  local source, original = api.nvim_get_current_win(), api.nvim_get_current_buf()
  api.nvim_buf_set_lines(original, 0, 0, false, { "-- unsaved introduction" })
  api.nvim_win_set_cursor(0, { 4, 2 })
  h.press(" fr")
  local prompt = api.nvim_get_current_buf()
  local picker = require("telescope.actions.state").get_current_picker(prompt)
  wait(function() return picker.manager and picker.manager:num_results() == 3 end, "All review points must appear")
  h.equal(api.nvim_win_get_buf(source), original, "Opening search must not navigate")
  local other = vim.fn.bufnr(root .. "/b with spaces.lua")
  assert(not api.nvim_buf_is_loaded(other), "Search must not eagerly load unselected files")
  picker:set_prompt("result handling")
  wait(function() return picker.manager:num_results() == 1 end, "Review titles must be searchable")
  h.press("<CR>")
  wait(function() return api.nvim_get_current_buf() == other end, "Enter must jump to the selected file")
  h.equal(api.nvim_win_get_cursor(0)[1], 1, "Jump must target the review line")
  h.equal(#h.editor_windows(), 1, "Selection must leave no list panel")
  assert(vim.bo[original].modified, "Navigation must preserve unsaved edits")
  h.press(" rx")
  h.press(" fr")
  prompt = api.nvim_get_current_buf()
  picker = require("telescope.actions.state").get_current_picker(prompt)
  picker:set_prompt("REJECT")
  wait(function() return picker.manager and picker.manager:num_results() == 1 end, "Unsaved review status must be searchable")
  require("review.sync").apply({ root = root, task = "picker-update", items = {
    { id = "result", path = "b with spaces.lua", first = 1, last = 1, title = "fresh AI review" },
  } })
  wait(function() return picker.manager:num_results() == 0 end, "Changed review must leave the REJECT results immediately")
  picker:set_prompt("fresh AI review")
  wait(function() return picker.manager:num_results() == 1 end, "Open picker must receive updated AI review text")
  h.press("<Esc>")
  wait(function() return #h.editor_windows() == 1 end, "Cancel must close the picker")
  h.equal(api.nvim_get_current_buf(), other, "Cancel must preserve the source buffer")
  h.equal(api.nvim_buf_get_lines(other, 0, 1, false)[1], "local result = false", "Review decisions must not modify source")
  assert(not vim.bo[other].modified, "Decision must not create unsaved source edits")
  review.stop()
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: real Telescope search, Enter navigation, status search, cancel, lazy loading and unsaved edits")
vim.cmd("qa!")
