vim.opt.rtp:prepend(vim.fn.getcwd())
package.path = vim.fn.getcwd() .. "/tests/?.lua;" .. package.path
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local h = require("helpers")
local review, store, api = require("review"), require("review.store"), vim.api
review.setup({ auto_advance = false })
local plugin_root = vim.fn.getcwd()
local root = h.project()
local function status(id)
  for _, item in ipairs(store.load(root).items) do if item.id == id then return item.status end end
end
local ok, err = xpcall(function()
  vim.cmd("cd " .. vim.fn.fnameescape(root))
  vim.cmd.edit(root .. "/a.lua")
  local buf = api.nvim_get_current_buf()
  local original = api.nvim_buf_get_lines(buf, 0, -1, false)
  review.open({ root = root })
  review.mark("REJECT")
  h.equal(status("retry"), "REJECT", "Decision must persist locally")
  assert(not vim.bo[buf].modified, "Review must not dirty the source")
  h.equal(api.nvim_buf_get_lines(buf, 0, -1, false), original, "Source must remain byte-for-byte unchanged")
  local marks = api.nvim_buf_get_extmarks(buf, api.nvim_get_namespaces()["review.nvim"], 0, -1, { details = true })
  assert(marks[1][4].virt_lines[1][1][1]:find("retry logic", 1, true), "Description must be virtual text")
  review.close()
  assert(not vim.bo[buf].modified, "Exiting review must not require saving")
  h.equal(vim.fn.readfile(root .. "/a.lua"), original, "Review must not write source")
  api.nvim_buf_set_lines(buf, 0, 0, false, { "-- user edit" })
  review.toggle()
  h.equal(api.nvim_buf_get_name(0), root .. "/b with spaces.lua", "Pending must take precedence over a rejected resume point")
  review.next(1)
  h.equal(api.nvim_win_get_cursor(0)[1], 2, "Rejected anchor must follow inserted lines")
  review.mark("OK")
  review.close()
  assert(vim.bo[buf].modified, "Existing unsaved code must stay unsaved")
  h.equal(vim.fn.readfile(root .. "/a.lua"), original, "Exit must not autosave unrelated code")
  review.open({ root = root })
  api.nvim_set_current_buf(buf)
  local id = review.add("inspect result", 3, 3)
  assert(id, "Adding a review must succeed without a source comment")
  assert(api.nvim_buf_get_lines(buf, 2, 3, false)[1] == "  return false")
  review.stop()
  local data, version = store.load(root)
  local another = vim.deepcopy(data)
  another.items[1].status = "PENDING"
  store.save(root, another, version)
  assert(not pcall(store.save, root, data, version), "Stale editor must not overwrite another editor's decisions")
  assert(store.locate({ anchor = { "x" } }, { "x", "x" }) == nil, "Duplicate anchors must need relocation")
  assert(store.locate({ anchor = { "x" } }, { "y" }) == nil, "Changed code must need relocation")
  vim.cmd("silent write")
  -- A fresh Neovim must restore statuses from disk, without source markers.
  local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
  local saved = vim.rpcrequest(child, "nvim_exec_lua", 'vim.opt.rtp:prepend(...); return require("review.store").load(select(2,...))', { plugin_root, root })
  vim.fn.jobstop(child)
  h.equal(saved.items[1].status, "PENDING", "Fresh process must restore local decisions")
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: source-free decisions, virtual descriptions, persistence, edits, anchors and concurrent write protection")
vim.cmd("qa!")
