vim.opt.rtp:prepend(vim.fn.getcwd())
package.path = vim.fn.getcwd() .. "/tests/?.lua;" .. package.path
vim.g.mapleader = " "
local h = require("helpers")
local review = require("review")
local api = vim.api
review.setup({ auto_advance = false })
vim.env.XDG_DATA_HOME = vim.fn.tempname()
local root = h.project()
local ns = api.nvim_get_namespaces()["review.nvim"]

local ok, err = xpcall(function()
  vim.cmd("cd " .. vim.fn.fnameescape(root))
  vim.cmd.edit(root .. "/a.lua")
  h.press(" rv")
  h.press("]r")
  local target = api.nvim_get_current_buf()
  h.equal(api.nvim_buf_get_name(target), root .. "/b with spaces.lua", "Select a review other than the first pending item")
  api.nvim_win_set_cursor(0, { 1, 6 })
  h.press(" ru")
  h.press(" rv")
  h.equal(#h.editor_windows(), 1, "Toggle off should close the review list")
  h.equal(api.nvim_win_get_cursor(0), { 1, 6 }, "Toggle off should preserve the editing cursor")
  h.equal(api.nvim_buf_get_extmarks(target, ns, 0, -1, {}), {}, "Toggle off should remove review highlighting")
  api.nvim_buf_set_lines(target, 0, 0, false, { "-- inserted during normal editing" })
  api.nvim_exec_autocmds("TextChanged", { buffer = target })
  h.equal(api.nvim_buf_get_extmarks(target, ns, 0, -1, {}), {}, "Normal editing must not restore hidden highlights")
  vim.cmd("hide enew")
  h.press(" rv")
  h.equal(api.nvim_get_current_buf(), target, "Toggle on should return from unrelated editing to the last review file")
  h.equal(api.nvim_win_get_cursor(0), { 2, 6 }, "Resume should follow the review after inserted lines and preserve cursor offset")
  h.equal(api.nvim_buf_get_lines(target, 1, 2, false)[1], "local result = false", "Pause and resume must not insert markers")
  assert(#api.nvim_buf_get_extmarks(target, ns, 0, -1, {}) > 0, "Resume should restore highlights")
  for _ = 1, 3 do
    h.press(" rv")
    h.equal(#h.editor_windows(), 1, "Repeated pause should leave one editor window")
    h.press(" rv")
    h.equal(#h.editor_windows(), 1, "Repeated resume must not add a window")
  end
  review.stop()
  h.press(" rv")
  h.equal(api.nvim_buf_get_name(0), root .. "/a.lua", "ReviewStop should clear the resume point and start a fresh review")
  review.mark("OK")
  review.close()
  review.toggle()
  h.equal(api.nvim_get_current_buf(), target, "Pending must take precedence over an OK resume point")
  review.mark("REJECT")
  review.stop()
  review.toggle()
  h.equal(api.nvim_get_current_buf(), target, "Reject must be first when pending is empty, before earlier OK files")
  review.mark("OK")
  review.stop()
  review.toggle()
  h.equal(api.nvim_buf_get_name(0), root .. "/a.lua", "OK remains accessible when no pending or reject remains")
  review.stop()
end, debug.traceback)
vim.fn.delete(root, "rf")
vim.fn.delete(vim.env.XDG_DATA_HOME, "rf")
if not ok then io.stderr:write(err .. "\n"); vim.cmd("cquit 1") end
print("PASS: toggle, editing while paused, resume cursor, unsaved decisions, repeated toggles and stop")
vim.cmd("qa!")
